-- Add notifications table for persistent storage
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS id INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS userId INT NOT NULL;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS message TEXT NOT NULL;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS data JSON;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS `read` BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
